name: movie_mate_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  internet_connection_checker: ^3.0.1

  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_svg: ^2.0.7
  pretty_dio_logger: ^1.3.1
  animated_text_kit: ^4.2.3
  get_it: ^7.6.6
  flutter_bloc: ^8.1.3
  flutter_staggered_grid_view: ^0.7.0
  hive_generator: ^2.0.1
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.10.0



  dartz: ^0.10.1
  flutter_screenutil: ^5.9.0
  dio: ^5.4.0
  shimmer: ^3.0.0


  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/moviematelogo.png"
flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/logos/
    - assets/placeholders/

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
